server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/studentrecord'
    username: springstudent
    password: springstudent
  main:
    banner-mode: off
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          users-client-oidc:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/users-client-oidc"
            scope: openid
            client-name: users-client-oidc
          client-authorization-code:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: read
            client-name: client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000
logging:
  level:
    root: info
    org.springframework.security: trace
    org.springframework.oauth2: trace


