server:
  port: 8090

spring:
  user:
    name: maria
    password: maria
  datasource:
    url: 'jdbc:mysql://localhost:3306/studentrecord'
    username: springstudent
    password: springstudent
  main:
    banner-mode: off
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
logging:
  level:
    root: info
    org.springframework.security: trace
    org.springframework.security.oauth2: trace


